// Package remotejournal is the production wal.DurableLog: a fenced
// PostgreSQL journal reached directly from Go over pgx/v5, exclusively through
// the narrowly scoped SECURITY DEFINER functions installed by metadata-db
// migration 009_remote_journal (schema pfj). It is the ONLY production log
// implementation; the file WAL (+ paired replication) remains an explicit
// development / offline-mount / fault-test implementation.
//
// Properties the implementation upholds:
//
//   - No local state. An authority holds journal truth only in the
//     database plus bounded process memory (uncommitted staging and mirrors of
//     remote facts). It never creates .wal/.meta/.transition/.opstate files.
//   - Canonical bytes, encoded once. Every record is encoded to PFR1 exactly
//     once at staging; the identical bytes are the DB row, the hash/chain
//     input, the duplicate-comparison identity, and the retry body.
//   - Durable-before-visible. AppendBatchBuffered reserves contiguous LSNs
//     and stages bytes without durability; CommitThrough returns nil only
//     after a committed database transaction covers the range.
//   - UNKNOWN outcomes are resolved, not guessed. A lost commit response is
//     retried with byte-identical groups: the server folds byte-identical
//     duplicates (before quota) so the retry converges on the truth. Only a
//     proven fence/conflict/integrity failure poisons the log.
//   - Bounded everything. One write ≤ 1 MiB, one intent ≤ 8 MiB, one commit
//     group ≤ 128 records / 16 MiB, one replay page ≤ 256 records / 16 MiB,
//     and staging memory is capped.
//   - Database-time fencing. Every mutating call presents the branch writer
//     lease + fencing token + capability; the SQL layer validates them against
//     clock_timestamp(), never a caller clock.
package remotejournal

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/steerlabs/portablefs/vcs/internal/ctlrec"
	"github.com/steerlabs/portablefs/vcs/internal/wal"
)

// Config identifies one branch writer's claim on the remote journal.
type Config struct {
	// DSN is the restricted authority login: a LOGIN role GRANTed
	// portablefs_authority, able to execute only the approved pfj.* functions
	// (no table access). It must never be the volume-api/admin credential.
	DSN      string
	TenantID string
	VolumeID string
	Branch   string

	// Writer binding facts from the branch's exclusive write lease (the single
	// monotonic writer fence). Unused by OpenReadOnly.
	AttachSessionID     string
	LeaseID             string
	FencingToken        int64
	HolderID            string
	AuthorityInstanceID string

	// The manager-controlled runtime binding presented on every claim, append,
	// read, hash, and suspend. Decimal counters remain strings until checked
	// into PostgreSQL BIGINTs; AuthorityCapability is issued once by the
	// manager for this exact runtime and is never generated by the child.
	ManagerEpoch        string
	AuthorityRuntimeSeq string
	AuthorityRuntimeID  string
	AuthorityCapability string
	// ClaimOperationID is the manager-issued durable idempotency key for the
	// claim. It is required; retries of a lost response reuse it unchanged.
	ClaimOperationID string
	// ExpectedBaseCommitID optionally binds a new/resumed generation to the
	// manifest anchor already loaded by the caller. Empty lets the database
	// return the authoritative anchor for cold recovery.
	ExpectedBaseCommitID string

	// Backlog quotas installed when THIS claim creates a fresh generation
	// (existing generations keep their durable quota). Zero uses the server
	// defaults (4 GiB / 1 Mi records).
	QuotaBacklogBytes   int64
	QuotaBacklogRecords int64

	// ApplicationName tags pool connections (pg_stat_activity).
	ApplicationName string
	// MaxConns bounds the pool (default 4).
	MaxConns int32
	// TransactionPooler declares that DSN reaches a transaction-mode pooler
	// (PgBouncer/pgcat in transaction mode). In this mode connection startup
	// omits the three session timeout GUCs: pooled deployments MUST install
	// equivalent server-side database or role defaults (migration
	// 016_pooler_timeouts) because a pooler cannot preserve arbitrary
	// session state on the server connection that executes a later call.
	TransactionPooler bool
	// CallTimeout bounds one SQL call (default 30s).
	CallTimeout time.Duration
	// MaxStagedBytes bounds uncommitted staging memory (default 64 MiB).
	MaxStagedBytes int64
}

const (
	defaultMaxConns       = 4
	defaultCallTimeout    = 30 * time.Second
	defaultMaxStagedBytes = 64 << 20
	// retryBackoffFloor/Ceil bound the identical-bytes retry loop used to
	// resolve UNKNOWN outcomes.
	retryBackoffFloor = 250 * time.Millisecond
	retryBackoffCeil  = 5 * time.Second
)

// stagedRecord is one reserved-but-not-yet-durable row: the exact canonical
// bytes (PFR1 record or whole PFJ3 entry, encoded once) plus the precomputed
// hash/chain identity. For PFJ3 rows the admission facts ride INSIDE the
// bytes (the SQL-verified manifest preamble); factCount is mirrored here only
// to bound one commit group's total fact consumption.
type stagedRecord struct {
	seq       uint64
	payload   []byte
	hashHex   string
	tipAfter  [32]byte
	factCount int
}

// Log is a claimed (or read-only) remote journal generation. It implements
// wal.DurableLog. All exported methods are safe for concurrent use.
type Log struct {
	pool journalDB
	// livenessPool is the reserved single connection that answers the
	// capability-bound lease-facts probe. It is set by every production open
	// path and is NEVER used by the data plane, so the child's fencing clock
	// cannot queue behind its own apply/flush traffic. Direct struct literals
	// (tests, benchmarks, the discovery probe) leave it nil and speak through
	// the one seam they were given.
	livenessPool journalDB
	// life fences every request: no call outlives the process lifecycle
	// context supplied to Open (no context.Background in request paths).
	life     context.Context
	cfg      Config
	readOnly bool

	// Immutable claim identity.
	generationID string
	branchID     string
	epoch        uint64
	capability   string // manager-issued raw authority capability; never logged
	managerEpoch int64
	runtimeSeq   int64
	// recordCodec/controlCodec are the generation's immutable codec pair,
	// fixed at claim: (pfr1,pfc1) via Open, (pfj3,pfc2) via OpenV3.
	recordCodec  string
	controlCodec string

	mu                 sync.Mutex
	baseSeq            uint64
	physicalTrimmedSeq uint64
	baseDigest         [32]byte
	baseCommitID       string
	nextSeq            uint64   // reserved head (staged included)
	tip                [32]byte // chain tip over everything reserved
	durableSeq         uint64   // exclusive: seq < durableSeq is database-durable
	durableTip         [32]byte // chain tip at durableSeq
	staged             []stagedRecord
	stagedBytes        int64
	backlogBytes       int64 // database-reported durable backlog [base, durable)
	backlogRecords     int64
	quotaBytes         int64 // database-owned quotas (mirrored for admission)
	quotaRecords       int64
	advisoryCapacity   int64 // SetCapacity client-side advisory bound (0 = none)
	// controlDbFloorMs mirrors the generation's durable PFC2 database-time
	// floor (PFJ3 generations only; claim/append/adopt responses carry it as
	// a canonical decimal and it may never regress).
	controlDbFloorMs int64
	cut              wal.CheckpointCut
	hasCut           bool
	suspending       bool
	suspended        bool
	poisoned         bool
	poisonCause      error
	poisonedCh       chan struct{}

	// admissionMu serializes LSN reservation while still allowing ordinary
	// appends to stage during an in-flight database commit. On the uncommon
	// near-capacity refresh path it bridges the l.mu -> commitMu handoff, so no
	// second appender can change the candidate revision while the code waits
	// for the current commit and refreshes authoritative quota facts.
	admissionMu sync.Mutex
	// commitMu serializes CommitThrough network commits (group commit).
	commitMu sync.Mutex
}

type journalDB interface {
	QueryRow(context.Context, string, ...any) pgx.Row
	Query(context.Context, string, ...any) (pgx.Rows, error)
	Close()
}

var _ wal.DurableLog = (*Log)(nil)

func capabilityHashHex(capability string) string {
	sum := sha256.Sum256([]byte(capability))
	return hex.EncodeToString(sum[:])
}

func nullIfEmpty(value string) any {
	if value == "" {
		return nil
	}
	return value
}

// generationJSON mirrors pfj.generation_json (+ claim/head extras). Every
// BIGINT crosses JSON as a canonical decimal string and is required through a
// pointer so omitted zero-valued fields cannot masquerade as valid facts.
type generationJSON struct {
	GenerationID        string         `json:"generationId"`
	TenantID            string         `json:"tenantId"`
	VolumeID            string         `json:"volumeId"`
	BranchID            string         `json:"branchId"`
	BranchName          string         `json:"branchName"`
	Epoch               *decimalUint64 `json:"epoch"`
	RecordCodec         string         `json:"recordCodec"`
	ControlCodec        string         `json:"controlCodec"`
	BaseCommitID        string         `json:"baseCommitId"`
	BaseSeq             *decimalUint64 `json:"baseSeq"`
	BaseDigest          string         `json:"baseDigest"`
	NextSeq             *decimalUint64 `json:"nextSeq"`
	TipDigest           string         `json:"tipDigest"`
	PhysicalTrimmedSeq  *decimalUint64 `json:"physicalTrimmedSeq"`
	Status              string         `json:"status"`
	BacklogBytes        *decimalInt64  `json:"backlogBytes"`
	BacklogRecords      *decimalInt64  `json:"backlogRecords"`
	QuotaBacklogBytes   *decimalInt64  `json:"quotaBacklogBytes"`
	QuotaBacklogRecords *decimalInt64  `json:"quotaBacklogRecords"`
	WriterFence         *decimalInt64  `json:"writerFence"`
	AttachSessionID     string         `json:"attachSessionId"`
	LeaseID             string         `json:"leaseId"`
	HolderID            string         `json:"holderId"`
	AuthorityInstanceID string         `json:"authorityInstanceId"`
	ManagerEpoch        *decimalInt64  `json:"managerEpoch"`
	AuthorityRuntimeSeq *decimalInt64  `json:"authorityRuntimeSeq"`
	AuthorityRuntimeID  string         `json:"authorityRuntimeId"`
	ControlDbFloorMs    *decimalInt64  `json:"controlDbFloorMs"`
	ClaimedAt           *decimalInt64  `json:"claimedAt"`
	Cut                 *cutJSON       `json:"cut"`
	UpdatedAt           *decimalInt64  `json:"updatedAt"`

	// Claim/head extras.
	OperationID                string        `json:"operationId"`
	Created                    bool          `json:"created"`
	Resumed                    bool          `json:"resumed"`
	Current                    *bool         `json:"current"`
	Replayed                   bool          `json:"replayed"`
	WriterLeaseLive            *bool         `json:"writerLeaseLive"`
	DBTimeMs                   *decimalInt64 `json:"dbTimeMs"`
	RequestAuthorityRuntimeSeq *decimalInt64 `json:"requestAuthorityRuntimeSeq"`
}

type cutJSON struct {
	OperationID              string         `json:"operationId"`
	Epoch                    *decimalUint64 `json:"epoch"`
	Status                   string         `json:"status"`
	Watermark                *decimalUint64 `json:"watermark"`
	ExpectedHeadCommitID     string         `json:"expectedHeadCommitId"`
	TreeHash                 string         `json:"treeHash"`
	CanonicalRequestHash     string         `json:"canonicalRequestHash"`
	AuxiliaryBlobDigestsHash string         `json:"auxiliaryBlobDigestsHash"`
	CommitID                 string         `json:"commitId"`
}

func decodeDigest(hexDigest string) ([32]byte, error) {
	var out [32]byte
	raw, err := hex.DecodeString(hexDigest)
	if err != nil || len(raw) != 32 {
		return out, fmt.Errorf("remotejournal: malformed 32-byte hex digest %q", hexDigest)
	}
	copy(out[:], raw)
	return out, nil
}

// poolConfig builds the pgx pool configuration for one journal connection
// (split from connect so the pooler-mode startup-parameter contract is unit
// testable without a database).
func poolConfig(cfg Config) (*pgxpool.Config, error) {
	if cfg.DSN == "" {
		return nil, fmt.Errorf("remotejournal: DSN required")
	}
	pc, err := pgxpool.ParseConfig(cfg.DSN)
	if err != nil {
		return nil, fmt.Errorf("remotejournal: parse DSN: %w", err)
	}
	maxConns := cfg.MaxConns
	if maxConns <= 0 {
		maxConns = defaultMaxConns
	}
	pc.MaxConns = maxConns
	pc.MinConns = 0
	pc.HealthCheckPeriod = 30 * time.Second
	pc.ConnConfig.ConnectTimeout = 10 * time.Second
	// QueryExecModeExec keeps transaction poolers safe: it creates no
	// server-side prepared-statement state and uses the unnamed extended
	// protocol in one round trip. Re-parsing is negligible for this
	// single-shot SELECT workload.
	pc.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeExec
	if pc.ConnConfig.RuntimeParams == nil {
		pc.ConnConfig.RuntimeParams = map[string]string{}
	}
	appName := cfg.ApplicationName
	if appName == "" {
		appName = "portablefs-vcs"
	}
	pc.ConnConfig.RuntimeParams["application_name"] = appName
	if cfg.TransactionPooler {
		// A transaction pooler does not preserve arbitrary startup/session
		// parameters on the server connection that executes a later call.
		// Omit them completely (including DSN-supplied values); migration
		// 016_pooler_timeouts installs the equivalent database defaults for
		// pooled deployments.
		delete(pc.ConnConfig.RuntimeParams, "statement_timeout")
		delete(pc.ConnConfig.RuntimeParams, "lock_timeout")
		delete(pc.ConnConfig.RuntimeParams, "idle_in_transaction_session_timeout")
	} else {
		// Direct connections retain the session-pinned deadlines:
		// statement_timeout cannot take effect mid-statement when set inside
		// the function, so it must already be active when the SELECT begins.
		pc.ConnConfig.RuntimeParams["statement_timeout"] = "30000"
		pc.ConnConfig.RuntimeParams["lock_timeout"] = "5000"
		pc.ConnConfig.RuntimeParams["idle_in_transaction_session_timeout"] = "60000"
	}
	return pc, nil
}

func connect(ctx context.Context, cfg Config) (*pgxpool.Pool, error) {
	pc, err := poolConfig(cfg)
	if err != nil {
		return nil, err
	}
	pool, err := pgxpool.NewWithConfig(ctx, pc)
	if err != nil {
		return nil, fmt.Errorf("remotejournal: build pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("remotejournal: database unreachable: %w", err)
	}
	return pool, nil
}

// livenessPoolConfig builds the DEDICATED single-connection pool that answers
// pfj.authority_lease_facts and nothing else.
//
// The child's fencing deadline is only extended by a successful lease-facts
// answer; an ambiguous one (timeout included) never extends. Sharing the
// data-plane pool therefore made the fencing clock a function of write load:
// a saturating apply/flush workload holds every one of the (default 4)
// connections, the probe blocks in pgxpool waiting for one, its bounded
// context expires, nothing extends, and the armed deadline runs out — a
// child that is demonstrably healthy and applying records at full speed
// fences itself. Load, not failure, killed the authority.
//
// One connection is reserved, kept warm (MinConns = 1), and never handed to
// the data plane, so probe latency is one round trip regardless of how busy
// the journal is. It is deliberately NOT a fallback path or a retry: it is a
// separate channel, which is the only structure under which "the child is
// alive" cannot be starved by the child's own useful work.
func livenessPoolConfig(cfg Config) (*pgxpool.Config, error) {
	livenessCfg := cfg
	if livenessCfg.ApplicationName == "" {
		livenessCfg.ApplicationName = "portablefs-vcs"
	}
	livenessCfg.ApplicationName += "-liveness"
	pc, err := poolConfig(livenessCfg)
	if err != nil {
		return nil, err
	}
	pc.MaxConns = 1
	pc.MinConns = 1
	return pc, nil
}

// journalPool is the child's database seam: the data-plane pool plus the
// reserved liveness connection. It satisfies journalDB with the DATA pool, so
// every existing call site (and every error path's Close) keeps its exact
// meaning while owning both connections' lifetimes.
type journalPool struct {
	data     *pgxpool.Pool
	liveness *pgxpool.Pool
}

func (p *journalPool) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	return p.data.QueryRow(ctx, sql, args...)
}

func (p *journalPool) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	return p.data.Query(ctx, sql, args...)
}

func (p *journalPool) Close() {
	p.data.Close()
	p.liveness.Close()
}

// connectWithLiveness opens the data-plane pool and the reserved liveness
// connection together. A liveness connection that cannot be established fails
// the open: a managed child with no isolated fencing clock must never serve.
func connectWithLiveness(ctx context.Context, cfg Config) (*journalPool, error) {
	data, err := connect(ctx, cfg)
	if err != nil {
		return nil, err
	}
	pc, err := livenessPoolConfig(cfg)
	if err != nil {
		data.Close()
		return nil, err
	}
	liveness, err := pgxpool.NewWithConfig(ctx, pc)
	if err != nil {
		data.Close()
		return nil, fmt.Errorf("remotejournal: build liveness pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := liveness.Ping(pingCtx); err != nil {
		liveness.Close()
		data.Close()
		return nil, fmt.Errorf("remotejournal: liveness connection unreachable: %w", err)
	}
	return &journalPool{data: data, liveness: liveness}, nil
}

func normalize(cfg *Config) error {
	if cfg.TenantID == "" || cfg.VolumeID == "" || cfg.Branch == "" {
		return fmt.Errorf("remotejournal: tenant, volume, and branch are required")
	}
	if len(cfg.TenantID) > 512 || len(cfg.VolumeID) > 512 || len(cfg.Branch) > 512 {
		return fmt.Errorf("remotejournal: tenant, volume, and branch identifiers are bounded to 512 bytes")
	}
	if cfg.QuotaBacklogBytes < 0 || cfg.QuotaBacklogRecords < 0 || cfg.MaxConns < 0 ||
		cfg.CallTimeout < 0 || cfg.MaxStagedBytes < 0 {
		return fmt.Errorf("remotejournal: quotas, connection count, timeouts, and staging bounds cannot be negative")
	}
	if len(cfg.ExpectedBaseCommitID) > 512 {
		return fmt.Errorf("remotejournal: expected base commit id is bounded to 512 bytes")
	}
	if cfg.CallTimeout == 0 {
		cfg.CallTimeout = defaultCallTimeout
	}
	if cfg.MaxStagedBytes == 0 {
		cfg.MaxStagedBytes = defaultMaxStagedBytes
	}
	return nil
}

func runtimeBinding(cfg Config) (managerEpoch, runtimeSeq int64, err error) {
	managerEpoch, err = parsePositiveSQLBigint("manager epoch", cfg.ManagerEpoch)
	if err != nil {
		return 0, 0, err
	}
	runtimeSeq, err = parsePositiveSQLBigint("authority runtime sequence", cfg.AuthorityRuntimeSeq)
	if err != nil {
		return 0, 0, err
	}
	if cfg.AuthorityRuntimeID == "" || cfg.AuthorityCapability == "" {
		return 0, 0, fmt.Errorf("remotejournal: manager-issued authority runtime id and capability are required")
	}
	if len(cfg.AuthorityRuntimeID) > 512 || len(cfg.AuthorityCapability) > 4096 {
		return 0, 0, fmt.Errorf("remotejournal: authority runtime id/capability exceeds its protocol bound")
	}
	return managerEpoch, runtimeSeq, nil
}

// Open claims (or resumes) the branch's journal generation as the fenced
// writer and returns the live Log. A lost claim response is retried with the
// identical operation id + capability until it resolves; a replayed receipt
// that is no longer current fails with ErrFenced (never a usable claim).
func Open(ctx context.Context, cfg Config) (*Log, error) {
	if err := normalize(&cfg); err != nil {
		return nil, err
	}
	if cfg.AttachSessionID == "" || cfg.LeaseID == "" || cfg.FencingToken <= 0 ||
		cfg.HolderID == "" || cfg.AuthorityInstanceID == "" {
		return nil, fmt.Errorf("remotejournal: writer claim requires session/lease/fence/holder/authority facts")
	}
	if len(cfg.AttachSessionID) > 512 || len(cfg.LeaseID) > 512 || len(cfg.HolderID) > 512 ||
		len(cfg.AuthorityInstanceID) > 512 {
		return nil, fmt.Errorf("remotejournal: writer identity fields are bounded to 512 bytes")
	}
	managerEpoch, runtimeSeq, err := runtimeBinding(cfg)
	if err != nil {
		return nil, err
	}
	if cfg.ClaimOperationID == "" || len(cfg.ClaimOperationID) > 200 {
		return nil, fmt.Errorf("remotejournal: manager-issued claim operation id is required and bounded to 200 bytes")
	}
	pool, err := connectWithLiveness(ctx, cfg)
	if err != nil {
		return nil, err
	}
	l := &Log{
		pool: pool, livenessPool: pool.liveness, life: ctx, cfg: cfg,
		capability:   cfg.AuthorityCapability,
		managerEpoch: managerEpoch,
		runtimeSeq:   runtimeSeq,
		recordCodec:  wal.PFR1Codec,
		controlCodec: ctlrec.PFC1Codec,
		poisonedCh:   make(chan struct{}),
	}

	var quotaBytes, quotaRecords any
	if cfg.QuotaBacklogBytes > 0 {
		quotaBytes = cfg.QuotaBacklogBytes
	}
	if cfg.QuotaBacklogRecords > 0 {
		quotaRecords = cfg.QuotaBacklogRecords
	}
	claimSQL := `SELECT pfj.journal_claim($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`
	claimArgs := []any{
		cfg.ClaimOperationID, cfg.TenantID, cfg.VolumeID, cfg.Branch,
		cfg.AttachSessionID, cfg.LeaseID, cfg.FencingToken, cfg.HolderID,
		cfg.AuthorityInstanceID, cfg.AuthorityCapability,
		managerEpoch, runtimeSeq, cfg.AuthorityRuntimeID,
		nullIfEmpty(cfg.ExpectedBaseCommitID), quotaBytes, quotaRecords,
	}
	invalidSuccesses := 0
	backoff := retryBackoffFloor
	for {
		raw, err := l.callIdempotent(claimSQL, claimArgs...)
		if err != nil {
			pool.Close()
			return nil, fmt.Errorf("remotejournal: claim: %w", err)
		}
		var head generationJSON
		invalid := error(nil)
		if err := json.Unmarshal(raw, &head); err != nil {
			invalid = fmt.Errorf("decode claim response: %w", err)
		} else if head.OperationID != cfg.ClaimOperationID || head.Current == nil {
			invalid = fmt.Errorf("claim response is missing the exact operation/current fields")
		} else if !*head.Current {
			pool.Close()
			return nil, fmt.Errorf("%w: claim receipt was superseded by a newer writer", ErrFenced)
		} else if err := l.adoptHead(&head, true); err != nil {
			invalid = err
		} else {
			return l, nil
		}

		invalidSuccesses++
		if invalidSuccesses >= maxInvalidSuccessBodies {
			pool.Close()
			return nil, fmt.Errorf("%w: claim %s returned %d invalid success bodies (last: %v)",
				ErrProtocolIntegrity, cfg.ClaimOperationID, invalidSuccesses, invalid)
		}
		select {
		case <-l.life.Done():
			pool.Close()
			return nil, fmt.Errorf("%w: claim %s reached its lifecycle deadline after invalid success: %v",
				ErrUnknownOutcome, cfg.ClaimOperationID, invalid)
		case <-time.After(backoff):
		}
		if backoff *= 2; backoff > retryBackoffCeil {
			backoff = retryBackoffCeil
		}
	}
}

// OpenReadOnly opens the branch's live generation without claiming a writer
// binding: replay and head reads work, every mutating method fails. It
// returns (nil, nil) when the branch has no live journal generation — the
// caller serves the branch head manifest directly.
func OpenReadOnly(ctx context.Context, cfg Config) (*Log, error) {
	if err := normalize(&cfg); err != nil {
		return nil, err
	}
	managerEpoch, runtimeSeq, err := runtimeBinding(cfg)
	if err != nil {
		return nil, err
	}
	pool, err := connectWithLiveness(ctx, cfg)
	if err != nil {
		return nil, err
	}
	l := &Log{
		pool: pool, livenessPool: pool.liveness, life: ctx, cfg: cfg, readOnly: true,
		capability:   cfg.AuthorityCapability,
		managerEpoch: managerEpoch,
		runtimeSeq:   runtimeSeq,
		recordCodec:  wal.PFR1Codec,
		controlCodec: ctlrec.PFC1Codec,
		poisonedCh:   make(chan struct{}),
	}
	head, err := l.fetchHead()
	if err != nil {
		pool.Close()
		return nil, err
	}
	if head == nil {
		pool.Close()
		return nil, nil
	}
	if err := l.adoptHead(head, false); err != nil {
		pool.Close()
		return nil, err
	}
	return l, nil
}

// fetchHead reads the redacted live-generation head (nil when none exists).
func (l *Log) fetchHead() (*generationJSON, error) {
	raw, err := l.callIdempotent(
		`SELECT pfj.journal_bound_head($1,$2,$3,$4,$5,$6,$7)`,
		l.cfg.TenantID, l.cfg.VolumeID, l.cfg.Branch,
		l.managerEpoch, l.runtimeSeq, l.cfg.AuthorityRuntimeID, l.capability,
	)
	if err != nil {
		return nil, fmt.Errorf("remotejournal: read journal head: %w", err)
	}
	if len(raw) == 0 || string(raw) == "null" {
		return nil, nil
	}
	var head generationJSON
	if err := json.Unmarshal(raw, &head); err != nil {
		return nil, fmt.Errorf("remotejournal: decode journal head: %w", err)
	}
	if head.RequestAuthorityRuntimeSeq == nil || int64(*head.RequestAuthorityRuntimeSeq) != l.runtimeSeq ||
		head.DBTimeMs == nil || int64(*head.DBTimeMs) <= 0 {
		return nil, fmt.Errorf("%w: bound head response is missing the exact request runtime/database time", ErrConflict)
	}
	return &head, nil
}

// adoptHead installs a claim/head snapshot as the Log's state mirror.
// asWriter additionally requires an active, correctly fenced binding.
func (l *Log) adoptHead(head *generationJSON, asWriter bool) error {
	validated, err := l.validateGenerationSnapshot(head, asWriter)
	if err != nil {
		return err
	}
	if asWriter && l.cfg.ExpectedBaseCommitID != "" && head.BaseCommitID != l.cfg.ExpectedBaseCommitID {
		return fmt.Errorf("%w: generation base commit %q does not match expected %q",
			ErrConflict, head.BaseCommitID, l.cfg.ExpectedBaseCommitID)
	}
	controlFloor := int64(0)
	if record, _ := l.codecPair(); record == pfj3RecordCodec {
		// The durable PFC2 control floor is a REQUIRED exact fact on every
		// PFJ3 generation snapshot: issuance binds it and appends advance it.
		if head.ControlDbFloorMs == nil || int64(*head.ControlDbFloorMs) < 0 {
			return fmt.Errorf("%w: PFJ3 generation snapshot is missing its canonical control floor", ErrProtocolIntegrity)
		}
		controlFloor = int64(*head.ControlDbFloorMs)
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	if controlFloor < l.controlDbFloorMs {
		return fmt.Errorf("%w: generation snapshot regressed the control floor (%d < %d)",
			ErrProtocolIntegrity, controlFloor, l.controlDbFloorMs)
	}
	l.generationID = head.GenerationID
	l.branchID = head.BranchID
	l.epoch = validated.epoch
	l.baseSeq = validated.baseSeq
	l.physicalTrimmedSeq = validated.physicalTrimmedSeq
	l.baseDigest = validated.baseDigest
	l.baseCommitID = head.BaseCommitID
	l.nextSeq = validated.nextSeq
	l.tip = validated.tipDigest
	l.durableSeq = validated.nextSeq
	l.durableTip = validated.tipDigest
	l.backlogBytes = validated.backlogBytes
	l.backlogRecords = validated.backlogRecords
	l.quotaBytes = validated.quotaBytes
	l.quotaRecords = validated.quotaRecords
	l.controlDbFloorMs = controlFloor
	l.cut, l.hasCut = validated.cut, validated.hasCut
	return nil
}

// ControlDbFloorMs reports the mirrored durable PFC2 control floor of a PFJ3
// generation (exact database milliseconds; 0 before any fact was consumed).
func (l *Log) ControlDbFloorMs() int64 {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.controlDbFloorMs
}

// applyGeneration refreshes the base/backlog/cut mirrors from a mutating
// call's returned generation snapshot (trim/rotate/suspend responses).
func (l *Log) applyGeneration(raw []byte) error {
	var g generationJSON
	if err := json.Unmarshal(raw, &g); err != nil {
		return fmt.Errorf("remotejournal: decode generation snapshot: %w", err)
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	validated, err := l.validateGenerationSnapshot(&g, true)
	if err != nil {
		return err
	}
	if err := l.validateGenerationTransition(&g, validated); err != nil {
		return err
	}
	l.baseSeq = validated.baseSeq
	l.physicalTrimmedSeq = validated.physicalTrimmedSeq
	l.baseDigest = validated.baseDigest
	l.baseCommitID = g.BaseCommitID
	l.backlogBytes = validated.backlogBytes
	l.backlogRecords = validated.backlogRecords
	l.cut, l.hasCut = validated.cut, validated.hasCut
	return nil
}

// Close releases the connection pool. It does not release the claim: the
// writer binding dies with the lease (database-time expiry) or is superseded
// by the next claimant's higher fence.
func (l *Log) Close() {
	l.pool.Close()
}

// ─── Small accessors (wal.DurableLog) ────────────────────────────────────────

// Bounds reports the frozen production admission bounds.
func (l *Log) Bounds() wal.LogBounds { return wal.ProductionLogBounds() }

// codecPair resolves this generation's immutable codec pair. A zero-value
// Log (tests constructing the struct directly) speaks the legacy pair.
func (l *Log) codecPair() (record, control string) {
	if l.recordCodec == "" {
		return wal.PFR1Codec, ctlrec.PFC1Codec
	}
	return l.recordCodec, l.controlCodec
}

// RecordCodec identifies this epoch's record encoding.
func (l *Log) RecordCodec() string { record, _ := l.codecPair(); return record }

// ControlCodec identifies this epoch's control-payload encoding.
func (l *Log) ControlCodec() string { _, control := l.codecPair(); return control }

// Epoch is the journal generation's digest-chain epoch (an identity, not a
// second lease clock).
func (l *Log) Epoch() uint64 { return l.epoch }

// GenerationID names the claimed journal generation.
func (l *Log) GenerationID() string { return l.generationID }

// BaseCommitID is the exact manifest anchor cold recovery loads (advanced
// only by proven logical trims).
func (l *Log) BaseCommitID() string {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.baseCommitID
}

// BaseDigest is the exact lowercase SHA-256 digest-chain value at
// CompactedThrough. Startup presents it to the independent history-serving
// proof so a commit id alone can never select a base.
func (l *Log) BaseDigest() string {
	l.mu.Lock()
	defer l.mu.Unlock()
	return hex.EncodeToString(l.baseDigest[:])
}

// Watermark is the exclusive upper bound of reserved LSNs (staged included).
func (l *Log) Watermark() uint64 {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.nextSeq
}

// DurableHead returns the exact exclusive database-durable revision. It does
// not include locally reserved/staged records. This is an observation only:
// lifecycle callers must close admission and use SuspendExact to atomically
// verify the same revision while changing the durable generation state.
func (l *Log) DurableHead() (nextSeq uint64, tipDigest string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.durableSeq, hex.EncodeToString(l.durableTip[:])
}

// CompactedThrough is the journal's logical base (records below it are
// checkpoint-covered and may be physically deleted at any time).
func (l *Log) CompactedThrough() uint64 {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.baseSeq
}

// BacklogBytes reports durable backlog plus uncommitted staging.
func (l *Log) BacklogBytes() int64 {
	l.mu.Lock()
	defer l.mu.Unlock()
	if total, ok := addNonnegativeInt64(l.backlogBytes, l.stagedBytes); ok {
		return total
	}
	// Both components are non-negative database/admission facts. Saturating
	// keeps observability and admission fail-closed instead of wrapping to a
	// negative value should a corrupt or future-expanded bound reach int64.
	return int64(^uint64(0) >> 1)
}

// SetCapacity installs an ADVISORY client-side backlog bound (0 clears it).
// The authoritative quota lives in the database (identical for every replica);
// the advisory bound can only be stricter.
func (l *Log) SetCapacity(bytes int64) {
	l.mu.Lock()
	l.advisoryCapacity = bytes
	l.mu.Unlock()
}

// QuotaBytes reports the database-owned backlog byte quota mirrored from the
// last claim/append/trim (the advisory bound, when stricter, wins so statfs
// reflects the bound writes actually hit).
func (l *Log) QuotaBytes() int64 {
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.advisoryCapacity > 0 && (l.quotaBytes == 0 || l.advisoryCapacity < l.quotaBytes) {
		return l.advisoryCapacity
	}
	return l.quotaBytes
}

// OverCapacity reports whether admission must stop BEFORE reserving more
// intents: the database quota (mirrored from the last claim/append/trim),
// the advisory bound, or the staging-memory cap would be exceeded.
func (l *Log) OverCapacity() bool {
	l.mu.Lock()
	defer l.mu.Unlock()
	pendingBytes, bytesOK := addNonnegativeInt64(l.backlogBytes, l.stagedBytes)
	pendingRecords, recordsOK := addNonnegativeInt64(l.backlogRecords, int64(len(l.staged)))
	if !bytesOK || !recordsOK {
		return true
	}
	if l.quotaBytes > 0 && pendingBytes >= l.quotaBytes {
		return true
	}
	if l.quotaRecords > 0 && pendingRecords >= l.quotaRecords {
		return true
	}
	if l.advisoryCapacity > 0 && pendingBytes >= l.advisoryCapacity {
		return true
	}
	return l.stagedBytes >= l.cfg.MaxStagedBytes
}

// Poison permanently fences the log.
func (l *Log) Poison() { l.poison(fmt.Errorf("remotejournal: poisoned by caller")) }

func (l *Log) poison(cause error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.poisonLocked(cause)
}

func (l *Log) poisonLocked(cause error) {
	if l.poisoned {
		return
	}
	l.poisoned = true
	l.poisonCause = cause
	close(l.poisonedCh)
}

// IsPoisoned reports whether the log refuses further mutations.
func (l *Log) IsPoisoned() bool {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.poisoned
}

// PoisonedCh is closed the moment the log is fenced.
func (l *Log) PoisonedCh() <-chan struct{} { return l.poisonedCh }

// DurabilityFacts returns the database's verifiable durability configuration
// for honest readiness evidence (a configuration string alone is not HA).
func (l *Log) DurabilityFacts(ctx context.Context) (map[string]any, error) {
	raw, err := l.callJSONB(ctx, `SELECT pfj.durability_facts()`)
	if err != nil {
		return nil, fmt.Errorf("remotejournal: durability facts: %w", err)
	}
	var facts map[string]any
	if err := json.Unmarshal(raw, &facts); err != nil {
		return nil, fmt.Errorf("remotejournal: decode durability facts: %w", err)
	}
	return facts, nil
}
