# syntax=docker/dockerfile:1.7

ARG GO_IMAGE=golang:1.26.5-bookworm@sha256:6c5605ab3a9a9fb3c4eafe5b3d63cdbf3881caf113262b67862547b54a9db599
ARG UBUNTU_IMAGE=ubuntu:24.04@sha256:561618e2c15bf2397621dd04f96926663a3b5616c189cf7e38db7e82f5c538ea

FROM ${GO_IMAGE} AS build
WORKDIR /source
COPY vcs/go.mod vcs/go.sum ./vcs/
RUN --mount=type=cache,id=portablefs-files-go-mod,target=/go/pkg/mod go -C vcs mod download
COPY vcs ./vcs
RUN --mount=type=cache,id=portablefs-files-go-build,target=/root/.cache/go-build \
    CGO_ENABLED=0 go -C vcs build -trimpath -ldflags='-s -w -buildid=' \
      -o /output/portablefs-files ./cmd/portablefs-files

FROM ${UBUNTU_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
    apt-get install --yes --no-install-recommends ca-certificates curl tini && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd --system --gid 200102 portablefs-files && \
    useradd --system --uid 200102 --gid 200102 --home-dir /var/lib/portablefs-files \
      --shell /usr/sbin/nologin portablefs-files && \
    install --directory --owner 200102 --group 200102 --mode 0700 /var/lib/portablefs-files && \
    install --directory --owner root --group root --mode 0755 /request-trust
COPY --from=build --chmod=0555 /output/portablefs-files /usr/local/bin/portablefs-files
USER 200102:200102
EXPOSE 4315
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/portablefs-files"]
