import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { decodePft2Node, encodePft2Node } from "./codec.js";
import { Pft2MemoryStore } from "./basetree.js";
import { pft2RefHex, pft2RefOf } from "./types.js";
import {
  buildGoldenFilesystem,
  buildGoldenRecovery,
  buildGoldenWideDirectory,
  objectSetHash,
  sampleNodes,
} from "./golden-shared.js";

interface GoldenVector {
  name: string;
  hex: string;
  digest: string;
  size: number;
}

interface GoldenTree {
  name: string;
  rootDigest: string;
  rootSize: number;
  objectCount: number;
  objectSetHash: string;
}

interface GoldenFile {
  version: number;
  vectors: GoldenVector[];
  trees: GoldenTree[];
}

// The shared cross-language golden file is generated by the Go twin:
//   PFT2_UPDATE_GOLDEN=1 go -C vcs test ./internal/pft2/ -run TestGolden
const goldenPath = fileURLToPath(new URL("../../../../testdata/pft2/golden.json", import.meta.url));

function loadGolden(): GoldenFile {
  return JSON.parse(readFileSync(goldenPath, "utf8")) as GoldenFile;
}

describe("pft2 golden vectors (Go <-> TS parity)", () => {
  const golden = loadGolden();

  it("covers every sample node exactly once", () => {
    const samples = sampleNodes();
    expect(golden.version).toBe(1);
    expect(golden.vectors.map((vector) => vector.name).sort()).toEqual([...samples.keys()].sort());
  });

  it("TS encoding reproduces every golden vector byte for byte", () => {
    const samples = sampleNodes();
    for (const vector of golden.vectors) {
      const node = samples.get(vector.name);
      expect(node, vector.name).toBeDefined();
      const encoded = encodePft2Node(node!);
      expect(Buffer.from(encoded).toString("hex"), vector.name).toBe(vector.hex);
      const ref = pft2RefOf(encoded);
      expect(pft2RefHex(ref), vector.name).toBe(vector.digest);
      expect(Number(ref.size), vector.name).toBe(vector.size);
    }
  });

  it("TS strictly decodes and re-encodes every golden vector identically", () => {
    for (const vector of golden.vectors) {
      const raw = new Uint8Array(Buffer.from(vector.hex, "hex"));
      const node = decodePft2Node(raw);
      const reencoded = encodePft2Node(node);
      expect(Buffer.from(reencoded).toString("hex"), vector.name).toBe(vector.hex);
    }
  });

  it("TS builders reproduce the golden filesystem object set exactly", () => {
    const tree = golden.trees.find((candidate) => candidate.name === "filesystem")!;
    expect(tree).toBeDefined();
    const store = new Pft2MemoryStore();
    const rootRef = buildGoldenFilesystem(store);
    expect(pft2RefHex(rootRef)).toBe(tree.rootDigest);
    expect(Number(rootRef.size)).toBe(tree.rootSize);
    expect(store.size).toBe(tree.objectCount);
    expect(objectSetHash(store)).toBe(tree.objectSetHash);
  });

  it("TS builders reproduce the golden recovery object set exactly", () => {
    const tree = golden.trees.find((candidate) => candidate.name === "recovery")!;
    expect(tree).toBeDefined();
    const store = new Pft2MemoryStore();
    const fsRoot = buildGoldenFilesystem(store);
    const recoveryRef = buildGoldenRecovery(store, fsRoot);
    expect(pft2RefHex(recoveryRef)).toBe(tree.rootDigest);
    expect(Number(recoveryRef.size)).toBe(tree.rootSize);
    expect(store.size).toBe(tree.objectCount);
    expect(objectSetHash(store)).toBe(tree.objectSetHash);
  });

  it("TS builders reproduce the golden multi-level directory tree exactly", () => {
    const tree = golden.trees.find((candidate) => candidate.name === "wide-directory")!;
    expect(tree).toBeDefined();
    const store = new Pft2MemoryStore();
    const rootRef = buildGoldenWideDirectory(store);
    expect(pft2RefHex(rootRef)).toBe(tree.rootDigest);
    expect(Number(rootRef.size)).toBe(tree.rootSize);
    expect(store.size).toBe(tree.objectCount);
    expect(objectSetHash(store)).toBe(tree.objectSetHash);
  });
});
